# Generated by Django 4.2.3 on 2023-11-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('input_image_url', models.URLField()),
                ('output_image_url', models.URLField()),
                ('fish1_actual', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1, null=True)),
                ('fish2_actual', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1, null=True)),
                ('fish3_actual', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1, null=True)),
                ('fish1_pred', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1, null=True)),
                ('fish2_pred', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1, null=True)),
                ('fish3_pred', models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=1, null=True)),
                ('result', models.CharField(choices=[('Correct', 'Correct'), ('False', 'False')], max_length=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=100)),
                ('input_image_url', models.URLField()),
                ('output_image_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('good_count', models.PositiveIntegerField(default=0)),
                ('bad_count', models.PositiveIntegerField(default=0)),
                ('user_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Results',
            },
        ),
    ]
